apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
spec:
   replicas: 1
   selector:
     matchLabels:
       app: grpc-service
   template:
     metadata:
       labels:
         app: grpc-service
     spec:
       containers:
       - name: grpc-service
         env:
         - name: MICRO_SERVER_ADDRESS
           value: ":50051"
         image: makubit/grpc-vs-rest-service_grpc-service:1.0.0
         imagePullPolicy: Always
         ports:
           - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: grpc-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-sorting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-sorting-service
  template:
    metadata:
      labels:
        app: grpc-sorting-service
    spec:
      containers:
        - name: grpc-sorting-service
          env:
          - name: MICRO_SERVER_ADDRESS
            value: ":50051"
          image: makubit/grpc-vs-rest-service_grpc-sorting-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50052

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-sorting-service
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50052
  selector:
    app: grpc-sorting-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-testing-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-testing-cli
  template:
    metadata:
      labels:
        app: grpc-testing-cli
    spec:
      containers:
        - name: grpc-testing-cli
          env:
            - name: MICRO_SERVER_ADDRESS
              value: ":50051"
          image: makubit/grpc-vs-rest-service_grpc-testing-cli:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: testing-port

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-testing-cli
  labels:
    name: grpc-testing-cli
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 30080 #accessible from outside of the cluser
  selector:
    app: grpc-testing-cli

  # minikube service api-service --url
# curl http://192.168.99.100:30080/gett

# importante:
# make build w testing cli
# docker tag grpc-testing-cli:latest makubit/grpc-vs-rest-service_grpc-testing-cli:latest
# docker push makubit/grpc-vs-rest-service_grpc-testing-cli:latest
# kubectl logs <pod> > logs

#awk '{ print $7 }' logs | tr -d "ms"
