// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/grpcService/grpcService.proto

package grpcService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortRequest struct {
	TableToSort          []int32  `protobuf:"varint,1,rep,packed,name=tableToSort,proto3" json:"tableToSort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortRequest) Reset()         { *m = SortRequest{} }
func (m *SortRequest) String() string { return proto.CompactTextString(m) }
func (*SortRequest) ProtoMessage()    {}
func (*SortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e2cc68dffee683, []int{0}
}

func (m *SortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortRequest.Unmarshal(m, b)
}
func (m *SortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortRequest.Marshal(b, m, deterministic)
}
func (m *SortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortRequest.Merge(m, src)
}
func (m *SortRequest) XXX_Size() int {
	return xxx_messageInfo_SortRequest.Size(m)
}
func (m *SortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SortRequest proto.InternalMessageInfo

func (m *SortRequest) GetTableToSort() []int32 {
	if m != nil {
		return m.TableToSort
	}
	return nil
}

type Response struct {
	Sorted               bool     `protobuf:"varint,1,opt,name=sorted,proto3" json:"sorted,omitempty"`
	SortedTable          []int32  `protobuf:"varint,2,rep,packed,name=sortedTable,proto3" json:"sortedTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e2cc68dffee683, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSorted() bool {
	if m != nil {
		return m.Sorted
	}
	return false
}

func (m *Response) GetSortedTable() []int32 {
	if m != nil {
		return m.SortedTable
	}
	return nil
}

func init() {
	proto.RegisterType((*SortRequest)(nil), "grpcService.SortRequest")
	proto.RegisterType((*Response)(nil), "grpcService.Response")
}

func init() {
	proto.RegisterFile("proto/grpcService/grpcService.proto", fileDescriptor_20e2cc68dffee683)
}

var fileDescriptor_20e2cc68dffee683 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2f, 0x2a, 0x48, 0x0e, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x45, 0x66, 0xeb,
	0x81, 0x65, 0x85, 0xb8, 0x91, 0x84, 0x94, 0xf4, 0xb9, 0xb8, 0x83, 0xf3, 0x8b, 0x4a, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x14, 0xb8, 0xb8, 0x4b, 0x12, 0x93, 0x72, 0x52, 0x43, 0xf2,
	0x41, 0xa2, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xac, 0x41, 0xc8, 0x42, 0x4a, 0x2e, 0x5c, 0x1c, 0x41,
	0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xf9, 0x45, 0x25, 0xa9,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x50, 0x1e, 0xc8, 0x14, 0x08, 0x2b, 0x04, 0xa4,
	0x51, 0x82, 0x09, 0x62, 0x0a, 0x92, 0x90, 0x51, 0x24, 0x17, 0xb7, 0x3b, 0xc2, 0x15, 0x42, 0x5e,
	0x5c, 0xa2, 0xee, 0xa9, 0x25, 0x6e, 0x45, 0xf9, 0xb9, 0x20, 0x3b, 0x32, 0xf3, 0xd2, 0x61, 0x12,
	0x12, 0x7a, 0xc8, 0xee, 0x47, 0x72, 0xa9, 0x94, 0x28, 0x8a, 0x0c, 0xcc, 0x49, 0x4a, 0x0c, 0x49,
	0x6c, 0x60, 0x5f, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xb2, 0xb7, 0x44, 0x0c, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GrpcService service

type GrpcServiceClient interface {
	GetFromSortingService(ctx context.Context, in *SortRequest, opts ...client.CallOption) (*Response, error)
}

type grpcServiceClient struct {
	c           client.Client
	serviceName string
}

func NewGrpcServiceClient(serviceName string, c client.Client) GrpcServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "grpcService"
	}
	return &grpcServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *grpcServiceClient) GetFromSortingService(ctx context.Context, in *SortRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "GrpcService.GetFromSortingService", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcService service

type GrpcServiceHandler interface {
	GetFromSortingService(context.Context, *SortRequest, *Response) error
}

func RegisterGrpcServiceHandler(s server.Server, hdlr GrpcServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&GrpcService{hdlr}, opts...))
}

type GrpcService struct {
	GrpcServiceHandler
}

func (h *GrpcService) GetFromSortingService(ctx context.Context, in *SortRequest, out *Response) error {
	return h.GrpcServiceHandler.GetFromSortingService(ctx, in, out)
}
